[project]
name = "playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyarrow>=19.0.1",
    "pyiceberg>=0.9.0",
    "s3fs>=2025.3.0",
]
